kind: pipeline
type: docker
name: default

trigger:
  event:
    - pull_request

clone:
  depth: 1

steps:
  - name: Install Dependencies
    image: node:10.20.1-alpine3.11
    commands:
      - yarn
  - name: Run Test
    image: node:10.20.1-alpine3.11
    commands:
      - echo "Test"
      - yarn test
  - name: Run Build
    image: node:10.20.1-alpine3.11
    commands:
      - echo "build"
      - yarn build