kind: pipeline
type: docker
name: default

trigger:
  event:
    - pull_request

steps:
  - name: Install Dependencies
    image: node:10.20.1-alpine3.11
    commands:
      - yarn
  - name: Run Test
    image: node:10.20.1-alpine3.11
    commands:
      - echo "Test"
      - yarn test
  - name: Run Build
    image: node:10.20.1-alpine3.11
    commands:
      - echo "build"
      - yarn build
  - name: Deploy to Firebase
    image: node:10.20.1-alpine3.11
    environment:
      FIREBASE_TOKEN:
        from_secret: FIREBASE_TOKEN
    commands:
      - echo "${FIREBASE_TOKEN}"
      - echo "TOKEN $${FIREBASE_TOKEN}"
      - npm install -g firebase-tools
      - firebase deploy --token "$${FIREBASE_TOKEN}"
    when:
      event:
        include:
        - push
      branch:
      - master